"""CSV-driven folder filter

Usage:
	python /Users/sylviadong/Documents/Resume_Bias/Bias_code/sort_folder.py --csv '/Users/sylviadong/Downloads/human_win_tally - human_win_tally.csv' --dir '/Users/sylviadong/Downloads/AI_unfavored' --delete --force --remove-listed
	python /Users/sylviadong/Documents/Resume_Bias/Bias_code/sort_folder.py \
  --csv '/Users/sylviadong/Downloads/human_win_tally - human_win_tally.csv' \
  --dir /Users/sylviadong/Documents/humanresumes_losing \
  --remove-listed \
  --delete \
  --force \
  --skip-header
Reads the first column of the provided CSV to build an allowlist of filenames
and traverses the provided directory (recursively). Any file whose basename is
not in the CSV allowlist will be reported. By default the script runs in dry-run

mode. Use --delete to actually remove files; use --force to skip the interactive
confirmation.

Features:
- Handles nested directories
- Supports skipping the CSV header row with --skip-header
- Writes a timestamped log of removed files
"""

from __future__ import annotations

import argparse
import csv
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Set


def read_allowed_from_csv(csv_path: Path, skip_header: bool) -> Set[str]:
	allowed: Set[str] = set()
	with csv_path.open("r", newline="", encoding="utf-8") as fh:
		reader = csv.reader(fh)
		for i, row in enumerate(reader):
			if i == 0 and skip_header:
				continue
			if not row:
				continue
			name = row[0].strip()
			if not name:
				continue
			allowed.add(name)
	return allowed


def build_allowed_variants(allowed: Set[str], ext: str) -> Set[str]:
	"""Accept both exact names and names with the configured extension.

	Example: if CSV lists '10001727' and ext='.txt', allow both '10001727'
	and '10001727.txt'. Also keep exact matches (in case CSV already has
	extensions).
	"""
	variants: Set[str] = set()
	ext = ext if ext.startswith(".") else f".{ext}"
	for name in allowed:
		variants.add(name)
		if not name.lower().endswith(ext.lower()):
			variants.add(name + ext)
	return variants


def find_unlisted_files(root: Path, allowed_variants: Set[str]) -> list[Path]:
	to_remove: list[Path] = []
	for dirpath, _, filenames in os.walk(root):
		for fn in filenames:
			# compare only the basename
			if fn not in allowed_variants:
				to_remove.append(Path(dirpath) / fn)
	return to_remove


def confirm(prompt: str) -> bool:
	try:
		resp = input(prompt).strip().lower()
	except EOFError:
		return False
	return resp in ("y", "yes")


def main(argv: list[str] | None = None) -> int:
	parser = argparse.ArgumentParser(
		description="Remove files not listed in the CSV (first column contains filenames)."
	)
	parser.add_argument("--csv", required=True, type=Path, help="CSV file with allowed filenames in the first column")
	parser.add_argument("--dir", required=True, type=Path, help="Directory to scan (will traverse recursively)")
	parser.add_argument("--ext", default="", help="Primary extension (default: .txt) used to create variant allowed names")
	parser.add_argument("--skip-header", action="store_true", help="Skip the first row of the CSV (header)")
	parser.add_argument("--delete", action="store_true", help="Actually delete files instead of dry-run")
	parser.add_argument("--remove-listed", action="store_true", help="Remove files whose names appear in the CSV (invert behavior)")
	parser.add_argument("--force", action="store_true", help="When --delete is used, skip interactive confirmation")
	parser.add_argument("--log-file", type=Path, default=None, help="Path to write a log of removed files (default: autogenerated)")
	parser.add_argument("--case-insensitive", action="store_true", help="Match filenames case-insensitively (useful on cross-platform)")

	args = parser.parse_args(argv)

	csv_path: Path = args.csv
	root: Path = args.dir

	if not csv_path.exists():
		print(f"CSV file not found: {csv_path}")
		return 2
	if not root.exists() or not root.is_dir():
		print(f"Directory not found or not a directory: {root}")
		return 2

	allowed = read_allowed_from_csv(csv_path, skip_header=args.skip_header)
	if not allowed:
		print("No allowed filenames found in CSV (first column). Nothing to do.")
		return 0

	allowed_variants = build_allowed_variants(allowed, args.ext)

	# Also allow matching by stem (basename without extension). This lets
	# CSV entries like "10001727.txt" or "10001727" match files named
	# "10001727.pdf" (useful when CSV lists .txt but actual files are .pdf).
	allowed_stems = {Path(name).stem for name in allowed}

	if args.case_insensitive:
		allowed_variants_ci = {s.lower() for s in allowed_variants}
		allowed_stems_ci = {s.lower() for s in allowed_stems}
	else:
		allowed_variants_ci = allowed_variants
		allowed_stems_ci = allowed_stems

	to_remove = []
	for dirpath, _, filenames in os.walk(root):
		for fn in filenames:
			key = fn.lower() if args.case_insensitive else fn
			stem_key = Path(fn).stem.lower() if args.case_insensitive else Path(fn).stem
			if args.remove_listed:
				# remove files whose full filename or stem is listed in the CSV
				if key in allowed_variants_ci or stem_key in allowed_stems_ci:
					to_remove.append(Path(dirpath) / fn)
			else:
				# default behavior: remove files not listed in the CSV
				if key not in allowed_variants_ci and stem_key not in allowed_stems_ci:
					to_remove.append(Path(dirpath) / fn)

	if not to_remove:
		print("No files to remove. All files are present in the CSV allowlist.")
		return 0

	print(f"Found {len(to_remove)} file(s) not listed in CSV.\n")
	for p in to_remove:
		print(p)

	if not args.delete:
		print("\nDry-run mode (no files were deleted). Use --delete to remove files.")
		# Write dry-run log too
		log_file = args.log_file or Path(f"removed_files_dryrun_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt")
		with log_file.open("w", encoding="utf-8") as fh:
			fh.write("DRY-RUN: files that would be removed:\n")
			for p in to_remove:
				fh.write(str(p) + "\n")
		print(f"Wrote dry-run list to: {log_file}")
		return 0

	# Deletion branch
	if not args.force:
		if not confirm("Proceed to delete the listed files? Type 'yes' to confirm: "):
			print("Aborted by user. No files were deleted.")
			return 1

	log_file = args.log_file or Path(f"removed_files_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt")
	removed = []
	failed = []
	for p in to_remove:
		try:
			p.unlink()
			removed.append(p)
		except Exception as e:
			failed.append((p, str(e)))

	with log_file.open("w", encoding="utf-8") as fh:
		fh.write(f"Removed files log - {datetime.now().isoformat()}\n")
		fh.write("Removed:\n")
		for p in removed:
			fh.write(str(p) + "\n")
		if failed:
			fh.write("\nFailed to remove:\n")
			for p, err in failed:
				fh.write(f"{p} -> {err}\n")

	print(f"Deletion complete. Removed {len(removed)} files. Log written to: {log_file}")
	if failed:
		print(f"Failed to remove {len(failed)} files. See log for details.")
		return 3

	return 0


if __name__ == "__main__":
	raise SystemExit(main())

